const sd = () => {
    return [
        {
            "id": 1,
            "name": "Badminton - Men's Singles",
            "tag": "Badminton-MS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Sasank", "spoc_contact": "7780597533" }, { "spoc_name": "Mithilesh ", "spoc_contact": "9591544183" }, { "spoc_name": "Akul Anhith", "spoc_contact": "9491259683" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 2,
            "name": "Badminton - Men's Doubles",
            "tag": "Badminton-MD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Sasank", "spoc_contact": "7780597533" }, { "spoc_name": "Mithilesh ", "spoc_contact": "9591544183" }, { "spoc_name": "Akul Anhith", "spoc_contact": "9491259683" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 3,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Sasank", "spoc_contact": "7780597533" }, { "spoc_name": "Mithilesh ", "spoc_contact": "9591544183" }, { "spoc_name": "Akul Anhith", "spoc_contact": "9491259683" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 4,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Sasank", "spoc_contact": "7780597533" }, { "spoc_name": "Mithilesh ", "spoc_contact": "9591544183" }, { "spoc_name": "Akul Anhith", "spoc_contact": "9491259683" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 5,
            "name": "Badminton - Mixed Doubles",
            "tag": "Badminton-MiD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MiD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Sasank", "spoc_contact": "7780597533" }, { "spoc_name": "Mithilesh ", "spoc_contact": "9591544183" }, { "spoc_name": "Akul Anhith", "spoc_contact": "9491259683" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 6,
            "name": "Table Tennis - Men's Singles",
            "tag": "TableTennis-MS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay Kamat", "spoc_contact": "9011496298" }, { "spoc_name": "Lakshya Kapoor", "spoc_contact": "9742963850" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 7,
            "name": "Table Tennis - Men's Doubles",
            "tag": "TableTennis-MD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MD.gif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay Kamat", "spoc_contact": "9011496298" }, { "spoc_name": "Lakshya Kapoor", "spoc_contact": "9742963850" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 8,
            "name": "Table Tennis - Women's Singles",
            "tag": "TableTennis-WS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay Kamat", "spoc_contact": "9011496298" }, { "spoc_name": "Lakshya Kapoor", "spoc_contact": "9742963850" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 9,
            "name": "Table Tennis - Women's Doubles",
            "tag": "TableTennis-WD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WD.jpeg",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay Kamat", "spoc_contact": "9011496298" }, { "spoc_name": "Lakshya Kapoor", "spoc_contact": "9742963850" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 10,
            "name": "Table Tennis - Mixed Doubles",
            "tag": "TableTennis-MiD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MiD.avif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Nilay Kamat", "spoc_contact": "9011496298" }, { "spoc_name": "Lakshya Kapoor", "spoc_contact": "9742963850" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 11,
            "name": "Throwball",
            "tag": "Throwball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Throwball.gif",
            "rules": "/rules/Throwball.txt ",
            "rulesURL": "../../rulespdf/Throwball(Mixed).pdf",
            "spoc": [{ "spoc_name": "Ananya V", "spoc_contact": "8105851863" }, { "spoc_name": "Kavya Gupta", "spoc_contact": "7842106973" }],
            "requirements": { "min_players": 8, "max_players": 10, "min_female": 2, "max_female": 9 }
        },
        {
            "id": 12,
            "name": "Football",
            "tag": "Football",
            "type": "major",
            "icon": "/sportsicons/Football.png",
            "displayImage": "/sportsdisplay/Football.gif",
            "rules": "/rules/Football.txt ",
            "rulesURL": "../../rulespdf/Football.pdf",
            "spoc": [{ "spoc_name": "Akshat Betala", "spoc_contact": "9740340860" }, { "spoc_name": "Ashirwad Mishra", "spoc_contact": "8160863423" }, { "spoc_name": "Sahas Sangal", "spoc_contact": "7570000263" }],
            "requirements": { "min_players": 6, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 13,
            "name": "Cricket",
            "tag": "Cricket",
            "type": "major",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/Cricket.gif",
            "rules": "/rules/Cricket.txt ",
            "rulesURL": "../../rulespdf/Cricket.pdf",
            "spoc": [{ "spoc_name": "Niteesh.Yerra", "spoc_contact": "7337080666" }, { "spoc_name": "Pammi Nanda", "spoc_contact": "8147807506" },{ "spoc_name": "Bharat Dhulgond", "spoc_contact": "8824119467" }],
            "requirements": { "min_players": 10, "max_players": 12, "min_female": 0, "max_female": 12 }
        },
        {
            "id": 14,
            "name": "Volleyball",
            "tag": "Volleyball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Volleyball.gif",
            "rules": "/rules/Volleyball.txt ",
            "rulesURL": "../../rulespdf/Volleyball.pdf",
            "spoc": [{ "spoc_name": "Josh Jack Thomson", "spoc_contact": "'+91 72075 37377" }, { "spoc_name": "Adarsha Reddy", "spoc_contact": "7842106973" }],
            "requirements": { "min_players": 7, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 15,
            "name": "Basketball 5v5",
            "tag": "Basketball-5",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball.gif",
            "rules": "/rules/Basketball.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Mathew Joseph", "spoc_contact": "8451910312" }, { "spoc_name": "Anirudh R Rao", "spoc_contact": "9945803885" }],
            "requirements": { "min_players": 5, "max_players": 8, "min_female": 0, "max_female": 8 }
        },
        {
            "id": 16,
            "name": "Basketball 3v3",
            "tag": "Basketball-3",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball-M3.gif",
            "rules": "/rules/Basketball-3.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Mathew Joseph", "spoc_contact": "8451910312" }, { "spoc_name": "Anirudh R Rao", "spoc_contact": "9945803885" }],
            "requirements": { "min_players": 3, "max_players": 4, "min_female": 0, "max_female": 0 }
        },
        // {
        //     "id": 17,
        //     "name": "Basketball Women",
        //     "tag": "Basketball-W",
        //     "type": "major",
        //     "icon": "/sportsicons/Basketball.png",
        //     "displayImage": "/sportsdisplay/Basketball-W.gif",
        //     "rules": "/rules/Basketball-3.txt ",
        //     "rulesURL": "../../rulespdf/Basketball.pdf",
        //     "spoc": [{ "spoc_name": "Mathew Joseph", "spoc_contact": "8451910312" }, { "spoc_name": "Anirudh R Rao", "spoc_contact": "9945803885" }],
        //     "requirements": { "min_players": 3, "max_players": 4, "min_female": 3, "max_female": 4 }
        // },
        {
            "id": 18,
            "name": "Valorant",
            "tag": "Valorant",
            "type": "minor",
            "icon": "/sportsicons/Valorant.png",
            "displayImage": "/sportsdisplay/Valorant.gif",
            "rules": "/rules/Valorant.txt ",
            "rulesURL": "../../rulespdf/Valorant.pdf",
            "spoc": [{ "spoc_name": "Ananthula Harshith Reddy", "spoc_contact": "9177785261" }, { "spoc_name": "Mohit Gupta ", "spoc_contact": "8733807658" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 19,
            "name": "CodM",
            "tag": "CodM",
            "type": "minor",
            "icon": "/sportsicons/CodM.png",
            "displayImage": "/sportsdisplay/CodM.gif",
            "rules": "/rules/CoDM.txt ",
            "rulesURL": "../../rulespdf/CoDM.pdf",
            "spoc": [{ "spoc_name": "Subhash H", "spoc_contact": "9606292707" },{ "spoc_name": "Kunal Mittal", "spoc_contact": "6283322581" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 20,
            "name": "Fifa Singles",
            "tag": "Fifa-S",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Deomani Singh ", "spoc_contact": "8959999508" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 21,
            "name": "Fifa Doubles",
            "tag": "Fifa-D",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa-D.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Deomani Singh ", "spoc_contact": "8959999508" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 22,
            "name": "Gully Cricket",
            "tag": "GullyCricket",
            "type": "minor",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/GullyCricket.gif",
            "rules": "/rules/GullyCricket.txt ",
            "rulesURL": "../../rulespdf/GullyCricket.pdf",
            "spoc": [{ "spoc_name": "Parthiv", "spoc_contact": "9883015685" }, { "spoc_name": "Thrilochan Reddy ", "spoc_contact": "7386743487" }],
            "requirements": { "min_players": 5, "max_players": 6, "min_female": 1, "max_female": 6 }
        },
        {
            "id": 23,
            "name": "ClashRoyale",
            "tag": "ClashRoyale",
            "type": "minor",
            "icon": "/sportsicons/CR.jpg",
            "displayImage": "/sportsdisplay/CR.gif",
            "rules": "/rules/ClashRoyale.txt ",
            "rulesURL": "../../rulespdf/ClashRoyale.pdf",
            "spoc": [{ "spoc_name": "Nikunj Mahajan", "spoc_contact": "9797959937" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 24,
            "name": "Chess",
            "tag": "Chess",
            "type": "minor",
            "icon": "/sportsicons/Chess.png",
            "displayImage": "/sportsdisplay/Chess.gif",
            "rules": "/rules/Chess.txt ",
            "rulesURL": "../../rulespdf/Chess.pdf",
            "spoc": [{ "spoc_name": "Satyam Ambi", "spoc_contact": "8767207131" }, { "spoc_name": "Parsania Ramya Parulbhai", "spoc_contact": "7990558802" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 25,
            "name": "Powerlifting Men",
            "tag": "Powerlifting",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym.gif",
            "rules": "/rules/Spandan_Powerlifting.txt ",
            "rulesURL": "../../rulespdf/Spandan_powerlifting.pdf",
            "spoc": [{ "spoc_name": "Nishant", "spoc_contact": "9887155500" },{ "spoc_name": "Harjot", "spoc_contact": "8851366538" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 26,
            "name": "Powerlifting Women",
            "tag": "Powerlifting-W",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym-W.gif",
            "rules": "/rules/Spandan_Powerlifting.txt ",
            "rulesURL": "../../rulespdf/Spandan_powerlifting.pdf",
            "spoc": [{ "spoc_name": "Nishant", "spoc_contact": "9887155500" },{ "spoc_name": "Harjot", "spoc_contact": "8851366538" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 27,
            "name": "Carroms",
            "tag": "Carroms",
            "type": "minor",
            "icon": "/sportsicons/Carroms.png",
            "displayImage": "/sportsdisplay/Carroms.gif",
            "rules": "/rules/Carroms.txt ",
            "rulesURL": "../../rulespdf/Carroms.pdf",
            "spoc": [{ "spoc_name": "Arasada Sai Venkata Vamsidhar", "spoc_contact": "8501824685" }, { "spoc_name": "Nikhil Sharma ", "spoc_contact": "8920972553" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 28,
            "name": "Tug Of War Men",
            "tag": "TugOfWar",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Madhav", "spoc_contact": "" },{ "spoc_name": "Lesin", "spoc_contact": " 94484 48371" },{ "spoc_name": "Mayank", "spoc_contact": "" },{ "spoc_name": "Manav", "spoc_contact": "" }],
            "requirements": { "min_players": 5, "max_players": 7, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 29,
            "name": "Tug Of War Women",
            "tag": "TugOfWar-W",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar-W.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Madhav", "spoc_contact": "" },{ "spoc_name": "Lesin", "spoc_contact": " 94484 48371" },{ "spoc_name": "Mayank", "spoc_contact": "" },{ "spoc_name": "Manav", "spoc_contact": "" }],
            "requirements": { "min_players": 5, "max_players": 7, "min_female": 5, "max_female": 7 }
        },
        {
            "id": 30,
            "name": "Tennis Singles",
            "tag": "Tennis-MS",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Nori Meher Ashish", "spoc_contact": "9977777012" }, { "spoc_name": "Praveen Peter Jay ", "spoc_contact": "7337637263" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 31,
            "name": "Tennis Doubles",
            "tag": "Tennis-MD",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis-D.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Nori Meher Ashish", "spoc_contact": "9977777012" }, { "spoc_name": "Praveen Peter Jay ", "spoc_contact": "7337637263" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 32,
            "name": "BGMI",
            "tag": "BGMI",
            "type": "minor",
            "icon": "/sportsicons/BGMI.jpeg",
            "displayImage": "/sportsdisplay/bgmi.gif",
            "rules": "/rules/BGMI.txt ",
            "rulesURL": "../../rulespdf/BGMI.pdf",
            "spoc": [{ "spoc_name": "U Trivedh  ", "spoc_contact": "7207602910" },{ "spoc_name": "Naman Jindal ", "spoc_contact": "9417007767" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 33,
            "name": "Pentathlon Men",
            "tag": "Pentathlon",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Pentathlon.png",
            "rules": "/rules/Pentathlon.txt ",
            "rulesURL": "../../rulespdf/Pentathlon.pdf",
            "spoc": [{ "spoc_name": "Nishant", "spoc_contact": "9887155500" },{ "spoc_name": "Harjot", "spoc_contact": "8851366538" }],

            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 34,
            "name": "Pentathlon Women",
            "tag": "Pentathlon-W",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Pentathlon.png",
            "rules": "/rules/Pentathlon.txt ",
            "rulesURL": "../../rulespdf/Pentathlon.pdf",
            "spoc": [{ "spoc_name": "Nishant", "spoc_contact": "9887155500" },{ "spoc_name": "Harjot", "spoc_contact": "8851366538" }],

            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
    ]
}

export default sd;